steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull asia-south1-docker.pkg.dev/data-region-436609-j6/sample-nest-js/sample-nest-be:latest || exit 0'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/data-region-436609-j6/sample-nest-js/sample-nest-be:latest'
      - '--cache-from'
      - 'asia-south1-docker.pkg.dev/data-region-436609-j6/sample-nest-js/sample-nest-be:latest'
      - '.'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        gcloud,
        compute,
        instance-groups,
        managed,
        rolling-action,
        restart,
        sample-nest-js-ig,
        --zone=asia-south1-c,
      ]

images:
  - 'asia-south1-docker.pkg.dev/data-region-436609-j6/sample-nest-js/sample-nest-be:latest'
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
