# Base image
FROM node:20
# Create app directory
WORKDIR /usr/src/app
# Cache npm dependencies
VOLUME /root/.npm
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./
# Install app dependencies
RUN npm ci --cache /root/.npm
# Bundle app source
COPY . .
# Start the server using the development build
CMD ["npm", "run", "start:dev"]
# Expose container port
EXPOSE 80